### ISSUE TITLE
`SelectableMath` doesn't render selection with `provider` 6.0

### ISSUE THREAD

**Issue by p-mazhnik** [simpleclub-extended/flutter_math_fork#28]
`SelectableMath` doesn't render selection with `provider` 6.0.0

I use `macOS` and Chrome (web) / Android emulator, flutter 2.5.3

Steps to reproduce:
1. Run  the `example` app (I was getting `null-safety` issues, so I had to remove `flutter_tex` dependency first)
2. Type some expression and try to select it. You can't.

Issue disappears if I downgrade the `provider` dependency to `5.0.0`

**Comment by creativecreatorormaybenot** [comment]
Thanks for reporting the issue! I highly assume this is because of the **breaking change** in `6.0.0` that handles _nullable types_ when checking providers (see [changelog](https://pub.dev/packages/provider/changelog#600)).

Unfortunately, I will likely not be able to look into any soon. Do you think you could check provider usage for where this might be the case?
