### ISSUE TITLE
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/flutter_math_fork-0.5.0/lib/src/widgets/selection/gesture_detector_builder.dart:186:20: Error: The argument type 'void Function(TapDownDetails)' can't be assigned to the parameter type 'void Function(TapDragDownDetails)?'.

### ISSUE THREAD

**Issue by theappideasankit** [simpleclub-extended/flutter_math_fork#61]
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/flutter_math_fork-0.5.0/lib/src/widgets/selection/gesture_detector_builder.dart:186:20: Error: The argument type 'void Function(TapDownDetails)' can't be assigned to the parameter type 'void Function(TapDragDownDetails)?'.

**Comment by dani00995** [comment]
I have the same problem when starting IOS
`Launching lib/main.dart on iPhone 14 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                           43,4s
Failed to build iOS app
Error (Xcode): ../../../../hong-gildong/.pub-cache/hosted/pub.dev/flutter_math_fork-0.5.0/lib/src/widgets/selection/gesture_detector_builder.dart:186:20: Error: The argument type 'void Function(TapDownDetails)' can't be assigned to the parameter type 'void Function(TapDragDownDetails)?'.

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro Max.
`
pubspace.yaml
`version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6
  flutter_staggered_grid_view: ^0.6.2
  dropdown_button2: ^1.9.2
  firebase_storage: ^11.0.10
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.11
  shimmer: ^2.0.0
  animated_background: ^2.0.0
  share_plus: ^6.3.0
  get: ^4.6.5
  url_launcher: ^6.1.8
  flutter_html: ^2.2.1
  photo_view: ^0.14.0
  quickalert: ^1.0.1`
